# explain.py
#
# This file adds two "explanation" features for the teacher:
#
# 1. A word-by-word breakdown: shows which Santali word matches
#    which Hindi word, so a teacher can see the sentence's pieces.
#
# 2. A short, plain-language explanation of what KIND of sentence
#    this is (a question, an instruction, a greeting, etc).
#
# IMPORTANT DESIGN CHOICE: the explanation is generated by looking
# at the ORIGINAL HINDI sentence (which we understand well), not by
# asking an AI to interpret the Santali translation (which it barely
# knows). This avoids the AI confidently making up wrong explanations
# about a language it has very little real knowledge of — important
# for a tool used to teach children.

from translate import translate_hindi_to_santali


def get_word_breakdown(hindi_sentence: str):
    """
    Splits a Hindi sentence into individual words, translates each
    one separately, and returns a list of (hindi_word, santali_word) pairs.

    Note: translating words in isolation (without their sentence context)
    can sometimes be less accurate than translating the full sentence —
    this is a known trade-off, worth mentioning in your report. It's
    still useful as a rough guide for the teacher, not a perfect one.
    """
    # Remove common punctuation, then split into words by spaces
    cleaned = hindi_sentence.replace("।", "").replace("?", "").replace(",", "")
    words = [w for w in cleaned.split(" ") if w.strip() != ""]

    breakdown = []
    for word in words:
        santali_word = translate_hindi_to_santali(word)
        breakdown.append({"hindi": word, "santali": santali_word})

    return breakdown


def get_plain_explanation(hindi_sentence: str) -> str:
    """
    Returns a short, safe, rule-based explanation of what kind of
    sentence this is, and why it's used in a lesson. This uses simple
    keyword/pattern checks on the HINDI text (which we understand
    reliably) rather than asking an AI to interpret the Santali output.
    """
    text = hindi_sentence.strip()

    # --- Rule 1: is it a question? ---
    if text.endswith("?") or "क्या" in text or "कैसे" in text or "कौन" in text:
        return "This is a QUESTION. Use it to ask students something and wait for their answer."

    # --- Rule 2: is it a greeting? ---
    greeting_words = ["नमस्ते", "प्रभात", "शुभ", "कैसे हैं"]
    if any(word in text for word in greeting_words):
        return "This is a GREETING. Use it to open the lesson or welcome students."

    # --- Rule 3: is it an instruction/command? ---
    # Hindi instructions/commands often end in these common verb patterns.
    instruction_endings = ["िए", "ो", "ें", "करें"]
    if any(text.rstrip("।").endswith(ending) for ending in instruction_endings):
        return "This is an INSTRUCTION. Use it to tell students what action to do next."

    # --- Default: treat it as a general teaching statement ---
    return "This is a STATEMENT. Use it to introduce or explain something to the class."


# Lets you test this file on its own: "python explain.py"
if __name__ == "__main__":
    test_sentence = "आज हम गिनती सीखेंगे।"
    print("Hindi sentence:", test_sentence)
    print()
    print("Word breakdown:")
    for pair in get_word_breakdown(test_sentence):
        print(f"  {pair['hindi']}  ->  {pair['santali']}")
    print()
    print("Explanation:", get_plain_explanation(test_sentence))
